include:
  - board: nice_nano@2.0.0
    shield: pin_tester
  - board: nice_nano@2.0.0
    shield: divboard_left
  - board: nice_nano@2.0.0
    shield: divboard_right
  - board: nice_nano@2.0.0
    shield: settings_reset
