include:
  - board: nice_nano@2.0.0
    shield: pin_tester
  - board: nice_nano@2.0.0
    shield: divyoku_left
  - board: nice_nano@2.0.0
    shield: divyoku_right
  - board: nice_nano@2.0.0
    shield: settings_reset
